# Generated by Django 4.2.1 on 2023-09-01 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstaDepto',
            fields=[
                ('id_esta_depto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_esta_depto', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_pais', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(upload_to='galeria/'),
        ),
        migrations.CreateModel(
            name='Munici',
            fields=[
                ('id_munici', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_munici', models.CharField(max_length=150)),
                ('id_esta_depto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.estadepto')),
            ],
        ),
        migrations.AddField(
            model_name='estadepto',
            name='id_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.pais'),
        ),
    ]
