# Generated by Django 4.2.1 on 2023-09-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_estadepto_pais_alter_imagen_imagen_munici_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_login', models.CharField(max_length=255)),
                ('x_api_key', models.CharField(max_length=255)),
                ('x_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('x_currency_code', models.CharField(max_length=3)),
                ('x_first_name', models.CharField(max_length=255)),
                ('x_last_name', models.CharField(max_length=255)),
                ('x_phone', models.CharField(max_length=20)),
                ('x_ship_to_address', models.TextField()),
                ('x_ship_to_city', models.CharField(max_length=255)),
                ('x_ship_to_country', models.CharField(max_length=255)),
                ('x_ship_to_state', models.CharField(max_length=255)),
                ('x_ship_to_zip', models.CharField(max_length=10)),
                ('x_ship_to_phone', models.CharField(max_length=20)),
                ('x_description', models.TextField()),
                ('x_url_success', models.URLField()),
                ('x_url_error', models.URLField()),
                ('x_url_cancel', models.URLField()),
                ('http_origin', models.URLField()),
                ('x_company', models.CharField(max_length=255)),
                ('x_address', models.TextField()),
                ('x_city', models.CharField(max_length=255)),
                ('x_country', models.CharField(max_length=255)),
                ('x_state', models.CharField(max_length=255)),
                ('x_zip', models.CharField(max_length=10)),
                ('x_freight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('x_email', models.EmailField(max_length=254)),
                ('x_type', models.CharField(max_length=20)),
                ('x_method', models.CharField(max_length=20)),
                ('x_invoice_num', models.CharField(max_length=20)),
                ('custom_fields', models.JSONField()),
                ('x_visacuotas', models.CharField(max_length=10)),
                ('x_relay_url', models.URLField()),
                ('origen', models.CharField(max_length=255)),
                ('store_type', models.CharField(max_length=255)),
                ('x_discount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
